### ISSUE TITLE
Web Image has a hard-coded empty alt tag

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1108]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behaviour?**

The `alt` tag is empty.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Render an Image on the web

**What is the expected behaviour?**

Render an Image on the web with an appropriate `alt` tag

**Comment by aronshamash** [comment]
I think we have an issue with alt text at The Times. The current site uses the image `caption` field from Methode which does not describe the image. It would also cause the caption to be read out twice by a screen reader so it is also therefore redundant. See below

<img width="1440" alt="screen shot 2018-07-17 at 11 44 52" src="https://user-images.githubusercontent.com/1736782/42813083-b2d8c4ca-89b7-11e8-9071-136ce14da591.png">

**Comment by aronshamash** [comment]
in this case `alt=""` is probably the best option.

**Comment by aronshamash** [comment]
We are going to use a new `altText` field from Methode so closing this issue.
