### ISSUE TITLE
iOS italic fonts are missing

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1109]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behaviour?**

When a font is set to italic, it will only be picked up if a fontFamily is not set. If one _is_ set, the italic style is overriden. This is for native iOS.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Check out the upcoming Key Facts default story, or add a `<Text>` Component with the following styles:

```
fontFamily: "TimesDigitalW04",
fontStyle: "italic"
```

**What is the expected behaviour?**

It should be _italic_

**Comment by CoreFloDev** [comment]
@colincclark That's weird how do you setup that the font name is `TimesDigitalW04` ?

On Android, there is no such font, it will be `TimesDigitalW04_italic`, the fontStyle doesn't change anything

**Comment by colincclark** [comment]
Component needed to be written using the appropriate font
