### ISSUE TITLE
Use React Context passing native callbacks

### ISSUE THREAD

**Issue by tuncaulubilge** [newsuk/times-components#1158]
Native callbacks (such as onTopicPress, onArticlePress etc.) is passed using props at the moment, but this can be simplified by utilising the new context package. 

Native app packages (android-app and ios-app) provide the callbacks via context and leafs (such as article-byline) should consume it. Storybooks and test can then create their own mock callbacks via the same context.

**Comment by ValGeorgiev** [comment]
This should not be an issue anymore. I will close it
