### ISSUE TITLE
Gesture test `animate back to the start after release` is "skipped"

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1180]
**Do you want to request a _feature_ or report a _bug_?**

A test in the gesture package, with the name value `animate back to the start after release` is currently commented out because it is flakey. The `scale` value keeps intermittently changing in the snapshots which fails the test. This test should be fixed so it can be uncommented and bring the package coverage to 100%

https://github.com/newsuk/times-components/pull/1179/files#diff-1af5a470d85943bf899d8b715bdcbe54R234

**Comment by ValGeorgiev** [comment]
This package doesn't exist anymore. I will close this one.
