### ISSUE TITLE
Iterator to take extra args for setup/teardown

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1186]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behaviour?**

The `iterator` helper in `test-utils` currently only takes an array fo tests and sets up those tests, numerically. It would be beneficial if the API handled setup and teardown functions so we could do away with annoying empty `describe` methods elsewhere

**Comment by ValGeorgiev** [comment]
This is not needed anymore, I will close it.
