### ISSUE TITLE
Going to fullscreen brightcove-video not working on Android

### ISSUE THREAD

**Issue by adrienthiery** [newsuk/times-components#121]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behaviour?**

When pressing the `expand` icon on the Android brightcove player, it just hides the controls.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Run `yarn storybook-native`, then `yarn android`, go to the Brightcove player story and try to go fullscreen.

**What is the expected behaviour?**

When pressing the `expand` icon on the Android brightcove player, the video should go fullscreen.

**Please mention other relevant information such as the browser version, Node.js version and Operating System.**

Tested on Android 6.0 emulator, with node v8, yarn latest, on MacOS Sierra 10.12.6
Works well on iOS
I tried to debug it and the [`EventType.ENTER_FULL_SCREEN` event](
https://docs.brightcove.com/en/player/mobile-sdks/brightcove-player-sdk-for-android/samples/code-examples.html#Fullscreen_mode) is indeed emitted, but nothing happens...

`08-02 09:34:09.540  3495  3495 V ButtonActionHandler: Emitting event: enterFullScreen`

Not sure if it is a problem with the wrapper or with the SDK itself. Any ideas on how to go on with that ?

**Comment by adrienthiery** [comment]
@aronshamash @dickie81 @jackharvey1 Do you have ideas or pointers on where the issue could come from ? 

I could spend some time on it but I'm not so sure where to begin...

**Comment by trevorah** [comment]
Hmm, our options are either to disable that button (:-1:) or have that button trigger an event that the component's parent could handle.

**Comment by dickie81** [comment]
@adrienthiery we have made some updates regarding android fullscreen - please checkout master and have a look.

**Comment by dickie81** [comment]
Also added enter/exit fullscreen events & a direct to fullscreen option. Should cover all eventualities.

**Comment by adrienthiery** [comment]
Yes, I saw that, that's on my to-do list for next week ! Thanks 🙂

**Comment by jukben** [comment]
I have the same problem with my (quite similar) implementation. Does someone figure out how to solve it? It really sounds like a bug in Brightcove itself.
