### ISSUE TITLE
bundle: remove react-native-web

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#1270]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behaviour?**

We ship react-native-web in the client bundle but it's huge, together with Apollo our vendor bundle is extremely large

**What is the expected behaviour?**

A lightweight babel transform that simply exchanges RN elements for Web with the ability to make semantic and style

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

Small bundle sizes, less dependencies, better perf etc.

**Comment by nathggns** [comment]
I think we might be underestimating how much React Native web does for us with this ticket. There's a ton of react native specific styling (`padding-vertical`), resolving of differences between react native's CSS specificity and the browsers, adding units to styles, etc. Then there's also stuff like knowing to load `.web` files etc. Probably a ton more but I'm just getting to grips with RNW. 

We *might* be able to utilise RNW as a transpile step into standard React code and ship that instead, but I've no idea how feasible that is.
