### ISSUE TITLE
bundle: add hydration checks

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#1301]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behaviour?**

it's possible to break the site by creating client side bundles that cannot hydrate the server rendered code plus it's a perf killer

**What is the expected behaviour?**

CI runs a hydration check for each of the bundles and exits with a non zero code if it errors

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

**Comment by nehasri89** [comment]
Needs more info
