### ISSUE TITLE
Error retry button clicks should go back to loading state while loading the data

### ISSUE THREAD

**Issue by tuncaulubilge** [newsuk/times-components#1331]
This issue is present in articles, topics and author profiles.

**Do you want to request a _feature_ or report a _bug_?**

It's an improvement on top of the current behaviour.

**What is the current behaviour?**

Users see the error view until loading finishes, so the retry button clicks give no visual feedback until the request is complete.

**What is the expected behaviour?**

We should provide some kind of a visual feedback. We should either show a loading spinner inside the retry button, giving the button extra states, or we can change the state of the whole view to loading.

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

Better UX. Users expect some feedback when they click the button.

**Comment by ValGeorgiev** [comment]
I will close this due to inactivity. I will reopen if the request comes from PO or editorial
