### ISSUE TITLE
Provide convenient way to show unteased content in storybook

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#1340]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behaviour?**

We don't allow headers to be configured from the storybook

**What is the expected behaviour?**

Can provide an auth token to be sent as an auth header to see unteased content in storybook

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

Easy to reproduce production errors in a dev environment for quick fixing. SSR should be able to accommodate this too locally

**Comment by nehasri89** [comment]
Needs more findings
