### ISSUE TITLE
fixtures: move to `gql` driven

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#1375]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behaviour?**

There are static `json` fixtures which are often wrong and/or become stale with time

**What is the expected behaviour?**

showcases/tests are driven by the underlying `gql` query

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

Fixtures become "live" and continually represent the actual API that times-components integrates with

**Comment by nehasri89** [comment]
Tools team are piking this up
