### ISSUE TITLE
Independently render the AuthorProfileHead component

### ISSUE THREAD

**Issue by himeshladva-ni** [newsuk/times-components#1401]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behaviour?**
There is no way of using the `<AuthorProfileHead />` component without using the `<AuthorProfile />` component. Have tried by using the `<AuthorProfile />` component, but we cannot supply our own provider for the `<ArticleList />` child component.
**If the current behaviour is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behaviour?**
To be able to do:
```js
const author = {
  name: 'David Aaronovitch',
  jobTitle: 'Columnist',
  twitter: 'DAaronovitch',
  biography: [...],
  image: 'davidaaronovitch.png'
};
<AuthorProfileHead author={author} />
```
And render the following:
![image](https://user-images.githubusercontent.com/3638119/46816400-ce8c4600-cd74-11e8-95ae-a81487dbab77.png)

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**
In author profile editor, we wish to display a live preview of the author profile whilst it is being edited. It would be better to use the same component that is used across the web and apps as this will render it as it should be displayed. 

**Please mention other relevant information such as the browser version, Node.js
version and Operating System.**
This is required for web, but should not be limited to just that.

**Comment by aronshamash** [comment]
`author-profile-head` needs to be broken out into its own package.

**Comment by aronshamash** [comment]
@himeshladva-ni it was separate about 6 months ago and it was decided that it should be in all in one package - we didn't think a client would need it separately.

**Comment by himeshladva-ni** [comment]
Okay, so when this is picked up we would just publish `v2.0.0` of `author-head`, rather than create a new package in npm entirely?

**Comment by aronshamash** [comment]
yes think so

**Comment by ValGeorgiev** [comment]
I will close this ticket due to inactivity. We can refactor author-profile-head and move it into a separate package when we have such request. This is not needed for now.
