### ISSUE TITLE
Article Page Findings | Date Publication component Issue

### ISSUE THREAD

**Issue by nehasri89** [newsuk/times-components#153]
When integrated with data, the display on web is not correct 

Expected for WEB:

- The component should not have the day
- Also the publication should be 
> The Times / The Sunday Times instead of Times / sundaytimes
Eg.
https://www.thetimes.co.uk/edition/news/critics-dismiss-ministers-plans-for-post-brexit-trade-6ng52xfct

**Comment by nehasri89** [comment]
the date format is agreed with UX

**Comment by thatportugueseguy** [comment]
@nehasri89 what are the values that we're getting from the api?
What are the possible values?

thank you
