### ISSUE TITLE
Upgrade to babel 7

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1540]
# BABEL 7 UPGRADE WRITE-UP

## Intro

The JS compiler babel was recently upgraded in August 2018 (https://babeljs.io/blog/2018/08/27/7.0.0) with an array of breaking changes, from version 6 to 7. Babel is not simply a singular package, but a collection of packages (plug-ins and presets) all of which are configurable and affect the resulting compiled code in different ways. These range from handling new JS (ES6+) coding syntax, to enabling the compilation of React and JSX code, as well as much more.

Our original task was to upgrade our React Native (RN) version from 0.55 to 0.57.5 to enable the new features and (mainly) to fix some issues around development debugging on the devices (see https://nidigitalsolutions.jira.com/browse/REPLAT-4303). As RN uses babel 7, we needed to bump this version as these packages are tightly coupled and one cannot simply use RN 0.57 with a lower version of babel than babel 7.

## Steps taken

Certain pre-upgrade steps were taken to ease the babel 7 transition. Linting tools were all bumped (https://github.com/newsuk/times-components/pull/1475 and https://github.com/newsuk/times-components/pull/1497) and flow was removed from the project (https://github.com/newsuk/times-components/pull/1502).

New TC branch: https://github.com/newsuk/times-components/compare/build/upgrade-babel?expand=1

https://babeljs.io/docs/en/v7-migration

* Used the npx babel upgrade tool (https://github.com/babel/babel-upgrade) which amends project dependencies to use the appropriate scoped packages (e.g. babel-preset-env -> @babel/preset-env)
* Ensure "babel-core": "^7.0.0-bridge-0" is used in packages that utilise jest (as well as using @babel/core) - https://jestjs.io/docs/en/getting-started#using-babel
* Changed the RN babel preset from babel-preset-react-native to metro-react-native-babel-preset
* Moved all .babelrc files to babel.config.js files (JSON to JS)
* Changed all the config files to use the new scoped packages and eschew shortcut plugin and preset names for the full names
* Changed all TC39 proposal plugins from “transform” to “proposal” (e.g. @babel/plugin-transform-class-properties -> @babel/plugin-proposal-class-properties)
* Had to remove various unused packages that were added with the babel-upgrade to pass linting
* Amended babel config options in webpack
* Had to upgrade all storybook packages (from 3.4.10 to ^4.0.0-alpha.25). This was because storybook now required a bump due to the new compiler version as the tools are tightly coupled. This introduced numerous breaking changes - in package names, method names and the way @storybook/addon-info passes stories through and the deprecation of the selectV2 knob)
* Had to upgrade webpack to version 4. This meant including the webpack CLI package as it has been split from the original package
* Had to upgrade graphQL and apollo packages as they also now use babel 7 and these packages were throwing numerous errors at this stage
* Had to upgrade haul (spoke to Tunca about this) as it also uses the latest babel version. This arguably could be removed at some point in the future

## Issues

Numerous issues with a multitude of packages occurred during the attempted upgrade (some mentioned above in steps taken). The worst head scratchers were / are:

* Numerous webpack issues caused by remaining .babelrc files - fixed in the above branch by converting to JS
* Storybook not loading stories - fixed in the above branch by fixing the storybook/config.js files and the way @storybook/addon-info in particular works
* yarn storybook (on web) now only loads to native files and components, causing numerous errors on web. This seems to be caused by React Native Web (RNW) not having been upgraded to babel 7, and the webpack and storybook changes seem to have borked this. There is a babel-plugin-react-native-web plugin in webpack-configurator which needs to be bumped to the version that uses babel 7, but as RNW itself does not work with B7 this does not work.

## To Do

1. RNW needs to be bumped in https://github.com/necolas/react-native-web/pull/1191 - this looks like it might take some time as the contributor says he is busy, and the code owner is not touching it
2. Web storybook needs to be run to see if it can cope with the .web files on the newer RNW version
3. Native storybook needs to be tested
4. TC tests need to be run and see if they work
5. RN will then be ready to bump (possibly on a separate branch, but it may all have to land at the same time)

**Comment by parkjh** [comment]
https://github.com/necolas/react-native-web/issues/1172

**Comment by necolas** [comment]
RNW shouldn't be blocking you. It only uses Babel to compile the source code before publishing to npm. I also won't be using `*.web.js` files as RN plans to move away from that pattern altogether

**Comment by tuncaulubilge** [comment]
Resolved
