### ISSUE TITLE
Caption and credit styles need reviewing

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#164]
*bug*

Taken screenshots of the current app vs our storybook story which show the differences between fonts and styles. Confirm with Azadeh and Jake

**What is the current behaviour?**

![screenshot_20170817-135939](https://user-images.githubusercontent.com/12942968/29432832-f3893010-8394-11e7-9955-d6300168f282.png)

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

![screenshot_20170817-135930](https://user-images.githubusercontent.com/12942968/29432890-21874614-8395-11e7-8478-5a47ef93524c.png)

**Comment by JGAntunes** [comment]
#197 fixed this no? @craigbilner

**Comment by sericaia** [comment]
Same as https://github.com/newsuk/times-components/issues/284
