### ISSUE TITLE
Profile page - Various styling issues

### ISSUE THREAD

**Issue by L0wry** [newsuk/times-components#171]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
Page not rendering correctly when compared to production

Author name is smaller
Author title is a different colour and has larger text
Missing twitter image
Missing twitter url
Profile image is being aligned left
Pagination count text darker shade and not being rendered inside `.Pagination-count`
Clicking next page take you to the homepage
Top padding of the article headline
Article date is `TIMES` or `SUNDAYTIMES` and not `The Times`  | `The Sunday Times`
Article Image is not being shown
Missing Pagination at the bottom of the page

TO CHECK: is article headline using cpi-page-title if it is present

![image](https://user-images.githubusercontent.com/12037104/29522539-6d15cd1e-8681-11e7-90c9-4609498b4862.png)

**If the current behaviour is a bug, please provide the steps to reproduce.**
Load story book in Safari 

**What is the expected behaviour?**
![screen shot 2017-08-21 at 15 00 37](https://user-images.githubusercontent.com/12037104/29522564-8c4e2910-8681-11e7-962e-8f74923853ac.png)

**Please mention other relevant information such as the browser version, Node.js version and Operating System.**

**Comment by sericaia** [comment]
@L0wry can you please confirm the this was fixed already?

**Comment by craigbilner** [comment]
has now been reviewed/released/reviewed
