### ISSUE TITLE
Author profile page: native experience on iOS

### ISSUE THREAD

**Issue by rjanjua** [newsuk/times-components#179]
**Do you want to request a *feature* or report a *bug*?**

Report a Bug

**What is the current behaviour?**

![screen shot 2017-08-24 at 17 46 51](https://user-images.githubusercontent.com/7603827/29678417-669e739c-88f6-11e7-944c-4c9ccaa927fe.png)

-  Image is not displayed (you see the default watermark instead)
-  The Pagination info is outside the section markers, it should be within
-  Cannot click through to twitter 
-  Twitter info does not have any twitter iconography
-  Cannot click through to articles

**If the current behaviour is a bug, please provide the steps to reproduce.**
Load up the author profile in storybook native

**What is the expected behaviour?**
This is a mock up of something that more closely resembles current behaviour on the web. I am not a designer, so take it with a pinch of salt.
![what it should look like](https://user-images.githubusercontent.com/7603827/29678666-5be3a804-88f7-11e7-9fe5-ddda91469b85.png)

**If this is a feature request, what is the motivation or use case for changing the behaviour?**

**Please mention other relevant information such as the browser version, Node.js version and Operating System.**
iOS

**Comment by sericaia** [comment]
1. Image is not displayed (you see the default watermark instead)
2. The Pagination info is outside the section markers, it should be within
3. Cannot click through to twitter
4. Twitter info does not have any twitter iconography
5. Cannot click through to articles

Everything is still not bahaving correctly. The only thing that I dont agree with is 2nd:
![image](https://user-images.githubusercontent.com/1150553/32506474-960bb8b2-c3dc-11e7-80ec-63ddc7f61dc6.png)

From this image you can see that the markers are supposed to have "< Prev" and "Next >" when they exist and the page number, as follows:
![image](https://user-images.githubusercontent.com/1150553/32506552-c30509cc-c3dc-11e7-9890-8888bce36d57.png)

Maybe we should not show Prev/Next when there is anything else.

**Comment by craigbilner** [comment]
has now been reviewed
