### ISSUE TITLE
BrightcovePlayerSDK/BrightcovePlayerSDK.h file not found

### ISSUE THREAD

**Issue by akshaygore06** [newsuk/times-components#1874]
I am unable to compile the projecct on iOS.
**Do you want to request a _feature_ or report a _bug_?**
Report a bug.

**What is the current behaviour?**
unable to compile a code on my curent environment. Always getting `........./node_modules/@times-components/brightcove-video/ios/RNTBrightcove/RNTBrightcoveView.h:4:9: fatal error: 'BrightcovePlayerSDK/BrightcovePlayerSDK.h' file not found
`

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
Work normally as it is working fine on Android.

**Please mention other relevant information such as the browser version, Node.js
version and Operating System.**

node@times-components/brightcove-video": "^2.1.3"
node: v9.11.1
npm : 5.6.0
Brightcove-Player-Core: 6.4.2

Xcode: 10
macOS: 10.13.6

**Comment by akshaygore06** [comment]
@tuncaulubilge Can you please help? Update: I tried downgrading the Xcode to 9.3 but I am still facing the same issue.

**Comment by tuncaulubilge** [comment]
@akshaygore06 unfortunately, this package has been deprecated as we are no longer using it, but I can try to help you with a possible fix.

This package relies on the native Brightcove SDKs, so make sure you have added Brightcove's iOS sdk in your app as well. See: https://support.brightcove.com/overview-brightcove-player-sdk-ios . Make sure you are getting the right version (`5.3.3`)

The readme also got a short guide on how to set up the library. : https://github.com/newsuk/times-components/tree/master/packages/brightcove-video

**Comment by ValGeorgiev** [comment]
I will close this due to inactivity and the mentioned package is deprecated and removed from the library.
