### ISSUE TITLE
[depend] Cannot find module @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by mrmlnc** [newsuk/times-components#1936]
**Do you want to request a _feature_ or report a _bug_?**

Most likely this is a bug after #1540 (https://github.com/newsuk/times-components/commit/e2c91831f6ed73c14e2ccf02ef9ccd581c7313a9#diff-c8c26c51ea165f1cd319ab6f78370c4fL67).

**What is the current behaviour?**

```console
Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- D:\OpenSource\tests\node_modules\@times-components\depend\dist\cli.js
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

```
npx @times-components/depend
```

**What is the expected behaviour?**

I see `--help` for the `depend` command like in ` @times-components/depend@2.1.15`.

**Please mention other relevant information such as the browser version, Node.js
version and Operating System.**

* `@types-components/depend`: `2.1.17`
* Windows 10
* Node.js: `10.15.3`, `12.2.0`

**Comment by ValGeorgiev** [comment]
This is not reproducible on МacOS. We don't have the capacity to test and fix it on Windows. This is an open-source project, so everyone can contribute to it. I will close this.
![image](https://user-images.githubusercontent.com/12056467/76358160-b3cf4f80-6321-11ea-86a2-8b142d7bbb4e.png)
