### ISSUE TITLE
Video stretches to fit player on Android

### ISSUE THREAD

**Issue by jackharvey1** [newsuk/times-components#21]
# Known issue/Bug

When accessing the `default` react-native Brightcove story on Android, which has the default `100%` width and height, then the video will stretch to fill the player rather than maintain the aspect ratio. 

Discussions were had over whether we could
a) Assume the aspect ratio
b) Fetch the aspect ratio from the metadata

However both of these result in the media controls moving up to the bottom of the video which we felt was undesirable.

**Comment by dickie81** [comment]
#128 fixes this - please review
