### ISSUE TITLE
[Brightcove] Multiple players can be playing at once on a single page

### ISSUE THREAD

**Issue by jackharvey1** [newsuk/times-components#215]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
Multiple videos can play at once on the same page

**If this is a feature request, what is the motivation or use case for changing the behaviour?**
Improved UX, so that users can move between videos easily on a single page without returning to pause the previous one.

**Comment by dickie81** [comment]
@jackharvey1 - I think this is for parent component / app to manage not something to be added to brightcove-video component itself.

**Comment by dickie81** [comment]
Closing as expected behaviour.
