### ISSUE TITLE
Needs analytics events

### ISSUE THREAD

**Issue by foliveira** [newsuk/times-components#27]
@craigbilner referred to this in his review of #12 and #22:

> (...) we also need to expose some more events for analytics (...) such as scroll depth and rendered (...)
> should we add an onload and onerror event for analytics (...) ?

What should be the guidelines for adding this and how would the integration work?

**Comment by trevorah** [comment]
Should we have some standard required props like `onUserAction` and `onPerfEvent` that get passed to children? `onUserAction` would be called with events like "Author Profile Viewed" and "Article Preview Clicked" (conventions via https://segment.com/academy/collecting-data/naming-conventions-for-clean-data).

If a component has something to report via `onUserAction`, it should mark that prop as required. I've lost too many days to tracking down why a analytics event hasn't been fired.

**Comment by foliveira** [comment]
Can we agree on a list of props that should be supported by every component? Or at least have a couple of events that we would definitely want to add support to?

Currently there are none in the in-dev components, but this is something that can be added later on - after we agree on what to add.

**Comment by craigbilner** [comment]
@foliveira - our component manifesto sort of says a component is shipped with events, atm we've agreed we'll just go with a set of "common-sense" ones

@trevorah - I think bringing it "in-house" with tests will help with the days lost piece anyway.

@sericaia has put [react-broadcast](https://github.com/mjackson/react-broadcast) into the ad stuff which ticks the boxes of

- [x] being able to sit transparently across components and communicate with them
- [x] allow for a common analytics layer to take generic events and decorate them before sending them to an endpoint at the appropriate time with batching etc

so potentially the `image` component for example, would broadcast `onload` and `onerror` on the `perf/lifecycle` channel and `clicked` on the `onUserAction` channel. Conceivably you could have layers of analytic "managers" so children of a section would be decorated with various bits and pieces, which is broadcast up to the "homepage" manager which decorates it before pinging it off so context can be kept local but the eventual result telling a whole story from a composed set of components

**Comment by fampinheiro** [comment]
I assume that the number of components that need to broadcast information will be plenty and a common solution would be preferable over having to wire each and every component.

I was thinking of a usage along these lines.

```js
import { Image } from "react-native";
import hasEventSource from "./event-source";

const EventSourceImage = hasEventSource(Image, {
  onLoad: {
    channel: 'perf/lifecycle/load'
  },
  onError: {
    channel: 'perf/lifecycle/error'
  },
  onClick: {
    channel: 'user/actions/click'
  }
})

export default (props) => {
  return <EventSourceImage {...props} />
}
```
