### ISSUE TITLE
Validation errors in dev mode

### ISSUE THREAD

**Issue by toboid** [newsuk/times-components#297]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
Certain areas in this codebase raise errors to warn developers about incorrect usage / errors that cannot be identified through static analysis. For example https://github.com/newsuk/times-components/blob/master/packages/tracking/tracking-context.js#L22 

**What is the expected behaviour?**
Raise errors when running locally, suppress errors for production builds.
Allow configuration to choose whether these errors will be raised as exceptions, written to the console as warnings or send to some other target such as an analytics endpoint.

**If this is a feature request, what is the motivation or use case for changing the behaviour?**
Allow rich validation in dev without affecting runtime performance or user experience.

**Please mention other relevant information such as the browser version, Node.js version and Operating System.**

**Comment by sericaia** [comment]
I agree, we need a proper ticket for this ;)

@craigbilner @trevorah

**Comment by aronshamash** [comment]
cannot be reproduced hence closing
