### ISSUE TITLE
Events not issued from brightcove-video when `directToFullscreen` option set

### ISSUE THREAD

**Issue by dickie81** [newsuk/times-components#318]
**BUG**

**What is the current behaviour?**

When (on iOS or Android platforms) `directToFullscreen` option is set no player events are sent.

**What is the expected behaviour?**

Player events should still be sent

**Comment by BernieSumption** [comment]
Closing this because fixing or working around it is part of the current Video work under REPLAT-153. Current plan is to play inline first and let the user go to full screen manually.

**Comment by aronshamash** [comment]
`brightcove-video` deprecated so closing
