### ISSUE TITLE
Android - article label not showing

### ISSUE THREAD

**Issue by L0wry** [newsuk/times-components#341]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
Label not loading
See attachment
**If the current behaviour is a bug, please provide the steps to reproduce.**
load article in react native

**What is the expected behaviour?**
article Labels loads

**Comment by sericaia** [comment]
![image](https://user-images.githubusercontent.com/1150553/32490534-640efdaa-c3ab-11e7-82f7-312f10185dd9.png)

Picture from Matt

**Comment by sericaia** [comment]
Could not reproduce now

![image](https://user-images.githubusercontent.com/1150553/32491031-10bf4da6-c3ad-11e7-82c8-b5d983a1b429.png)


Matt branch was old
