### ISSUE TITLE
When no components have changed in PR dextrose fails 

### ISSUE THREAD

**Issue by L0wry** [newsuk/times-components#450]
if no components have changed, for example when bumping package json version.

 ```No files were found matching the specified pattern. Story loader was not written.
/Users/vagrant/git/node_modules/@times-components/fructose/packages/test-helpers/bin/writeComponentsTests.js:48
          .split("\n")
           ^
```
results eventually in a bundler fail

 ```Unable to resolve module `./components` from `/Users/vagrant/git/fructose/index.js````

**Comment by kaliabadi** [comment]
https://github.com/newsuk/times-components/pull/452/files
