### ISSUE TITLE
Testing responsive components

### ISSUE THREAD

**Issue by toboid** [newsuk/times-components#472]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behaviour?**
Responsive features are tested by snapshotting css applied via media queries

**What is the expected behaviour?**
Find a better way to test responsive features. 
Investigate whether JSDOM will support css media queries.
Investigate other approaches such as fructose.

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**
More reliable testing

**Comment by craigbilner** [comment]
Now snaps have been re-written and web snaps having the necessary media queries, it's probably the best we can get from times-components for now. Ayespy should fill in any gaps too.
