### ISSUE TITLE
Improving snapshots

### ISSUE THREAD

**Issue by BernieSumption** [newsuk/times-components#589]
Snapshot testing could use some rationalising. Snapshots are too large, insufficiently readable, and often change as a result of distant refactorings in other parts of the codebase. Some of this may be fixable by writing and enforcing guidelines for snapshot best practices. The rest can be fixed with some simple utility functions to control what goes into snapshots.

Suggestions:

1. By default, don't let implementation details of one component leak into snapshot tests in another (shallow rendering is supposed to fix this, but sometimes we use enzyme.mount() or react-test-renderer for technical reasons, and these do full depth renders).

2. Provide a way for tests to either blacklist parts of the snapshot that they know are not relevant, or  to whitelist the parts that they are interested in.

3. Make an upper limit on the size of individual snapshots, potentially overridable. article.web.test.js.snap is 1.3MB in size with 11 snapshots.

**Comment by craigbilner** [comment]
Currently creating `jest-lint` to address point 3 and then we can extend @nikhedonia's serializer to provide better DX on the creation of snapshots
