### ISSUE TITLE
Brightcove does not display correctly on web

### ISSUE THREAD

**Issue by toboid** [newsuk/times-components#590]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Brightcove component does not display correctly when it's with and height props are set.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Example story - https://github.com/newsuk/times-components/blob/4bca29ecc4e8005242bcbdf5313df2efe81c4cbd/packages/brightcove-video/brightcove-video.stories.js#L81-L91
![image](https://user-images.githubusercontent.com/4660500/35731747-c9af0b80-080e-11e8-9d16-f1dd802dbe63.png)

Similar issue can be seen here - http://components.thetimes.co.uk/?selectedKind=BrightcoveVideo&selectedStory=Launcher%20fullscreen%20player%20with%20hidden%20Fullscreen%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**What is the expected behaviour?**
Displays correctly

**Comment by BernieSumption** [comment]
Closing this as it will be fixed as part of the video epic currently bring worked on under epic REPLAT-153.
