### ISSUE TITLE
Refactor Card and List Card

### ISSUE THREAD

**Issue by aronshamash** [newsuk/times-components#622]
### Problem
Currently Author profile list item uses `card` component. This is not reusable in the `slice` component. 

### Solution
Rename `card` component to `list-card`.
Abstract out the 'card' component used in related-articles in the `article` package into the new `card` component

**Comment by jimhunty** [comment]
Can you explain the problem?

**Comment by colincclark** [comment]
Card uses global media queries to determine when to wrap it's chid components. With related articles the wrapping was dependent on the number of related articles. Therefore, global media queries needs to be removed or replaced with a better system. `flex` could/should be able to manage this

**Comment by colincclark** [comment]
This is done
