### ISSUE TITLE
brightcove-video disable context menu

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#75]
*Feature*

**What is the current behaviour?**

Context menu is disabled at runtime - should probably be disabled at the config level?

[modal docs](https://docs.brightcove.com/en/player/brightcove-player/guides/player-info-modal.html)

**If this is a feature request, what is the motivation or use case for changing the behaviour?**

Won't be called at runtime and is a permanent config "fix"

**Comment by aronshamash** [comment]
brightcove-video component deprecated
