### ISSUE TITLE
transpile packages on postinstall

### ISSUE THREAD

**Issue by nikhedonia** [newsuk/times-components#770]
Currently package consumers need to use babel.
However we can speedup builds by building each package on postinstall.
In order to do this we need:
- move source to a src folder
- use babel to transpile into a dist folder
- adjust the entrypoint to point to dist/index.js
- provide a "dev" entrypoint for webpack for a good DX
- stories and __tests__  may need adjustments its imports

you may like to pick up my work at feat/transpile3 to get started.

**Comment by jamesseanwright** [comment]
Taking a look now. Thanks! :D

**Comment by jamesseanwright** [comment]
See /pull/786

**Comment by jamesseanwright** [comment]
Resolved by the merge of [/pull/786](https://github.com/newsuk/times-components/pull/786)
