### ISSUE TITLE
article@0.62.6 various bugs

### ISSUE THREAD

**Issue by L0wry** [newsuk/times-components#810]
Compare article pre react

<img width="1275" alt="pre-react" src="https://user-images.githubusercontent.com/12037104/38317380-dd3c10d0-3824-11e8-9272-b542c4dd4753.png">

to post react 
<img width="1250" alt="post-react" src="https://user-images.githubusercontent.com/12037104/38317402-ea0dc22c-3824-11e8-8f66-9c8de85f9dbd.png">

notice the spacing between the bylines is larger
there is also an extra line below the date
the colour of the byline is different

**Comment by aronshamash** [comment]
Please note there intentional design changes which are being introduced which should not be revert back to the current article page designs eg Byline spacing and date spacing. I believe this ticket is invalid.
