### ISSUE TITLE
Clear dist directories before transpiling

### ISSUE THREAD

**Issue by jamesseanwright** [newsuk/times-components#856]
When a source file is deleted, its transpiled counterpart it will still be present in its package's `dist` directory. This will result in superfluous, irrelevant code being shipped with our published modules.

Our `transpile` scripts should execute `[[ -e dist ]] && rm -r dist` before invoking `babel-cli`.

**Comment by colincclark** [comment]
https://github.com/newsuk/times-components/pull/868
