### ISSUE TITLE
Lazy loading and SSR for images should be standardized and reusable

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#871]
1. refactor Image for code coverage and DRYness
2. consolidate lazy loading into one package for reuse and testing
3. remove card imageSize as resize should all be done in Image package
4. ensure SSR works with image loading (default 100px)
5. make Image overridable so lazy loading can be bypassed
6. use .tar file download for native image cache - REPLAT-1002 - point JIRA ticket to deleted file

**What is the current behaviour?**

Lazy loading is embedded within the author profile package, but should be resuable across pages / other packages

**What is the expected behaviour?**

Most of the resize behaviour can be handled within Image, or within a lazy loading package (HOC / render prop, etc)

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

DRY code, consistent behaviour across devices

**Comment by craigbilner** [comment]
4. and 5. done in #1299 
3. not sure about this, quite expensive for say 20 images to each determine their own widths for example?

**Comment by craigbilner** [comment]
1. is now done
2. done in #1336
3. have pushed sizes into `Image` for handling art direction, high/low res determined by consumer
6. to be done separately #1355
