### ISSUE TITLE
Add Eslint rule for React Component destructuring

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#909]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behaviour?**

No lint rule

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

Linting fails if React.Component is not destructured

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

Increase code consistency

**Please mention other relevant information such as the browser version, Node.js
version and Operating System.**

**Comment by colincclark** [comment]
Done in https://github.com/newsuk/times-components/pull/970
