### ISSUE TITLE
Author profile and article list level page errors have images

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#918]
**What is the current behaviour?**

The image used in page level errors for author profile and topic pages are hard-coded external resources in the native file.  Search for `uri="https://www.thetimes.co.uk/d/img/internal-error-c45d0e8347.png"`

This error could (and in most cases probably would) be caused by failing network connectivity. In this case, the image won't load, so should probably be bought into the package, and loaded locally.

**Comment by aronshamash** [comment]
Other option could be to base64 it?

**Comment by colincclark** [comment]
Done in https://github.com/newsuk/times-components/pull/984
