### ISSUE TITLE
Remove unsafe React lifecycle events

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#965]
In the React release plan, there are a number of lifecycle events that are being deprecated. We should replace them with the newer lifecycle events to ensure a smooth transition to later React versions.

https://reactjs.org/docs/strict-mode.html

**Comment by craigbilner** [comment]
See #977 for use cases

**Comment by colincclark** [comment]
Completed with https://github.com/newsuk/times-components/pull/1201 and https://github.com/newsuk/times-components/pull/1247
