### ISSUE TITLE
React warnings in the Card storybook stories on native

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#967]
On native, for some of the Card stories, a warning shows:

`node of type at rule not supported as an inline style`

Needs investigation / fixing

**Comment by nathggns** [comment]
I'm pretty sure this is a complaint about media queries… isolated it down to `packages/card/card.showcase.js#CardWrapper/ReversedCardWrapper`

**Comment by nathggns** [comment]
I don't know if styled components supports media queries on styled components https://github.com/styled-components/styled-components/issues/203

**Comment by nathggns** [comment]
Fixed by #1388
