### ISSUE TITLE
Article list loading props are not consistent, or handled properly

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#989]
**Do you want to request a _feature_ or report a _bug_?**

Fix / Refactor

**What is the current behaviour?**

The way Article List handles loading states is confusing and wrong. `ArticleList` is being passed two loading states, `isLoading` and `articlesLoading` from author-profile, but only `articlesLoading` from topic. This should be standardised and more simple and easy to understand.

**What is the expected behaviour?**

- `isLoading` could be renamed to explicitly indicate whether to show the loading header state (`headerLoading` or similar). If this is not appropriate, then the refactor should standardise passing the loading header into `ArticleList` properly, which is not happening atm.
- `articlesLoading` should only manage the loading state of the Cards
- this needs standardising across `topic` and `author-profile` pacakges
- this needs standardising across web and native implementations

**Comment by nathggns** [comment]
As far as I can tell, the `isLoading` prop that is being passed into `ArticleList` is not being used at all, `articlesLoading` only affects the cards. 

Potentially just need to remove the `isLoading` prop that is being passed in because it doesn't do anything? 

Thoughts @craigbilner @colincclark

**Comment by colincclark** [comment]
`isLoading` is aliased to `articlesLoading` so they seem to be one and the same thing: https://github.com/newsuk/times-components/blob/master/packages/article-list/article-list.showcase.js#L85

`isLoading` comes from the `Provider`, and `articlesLoading` is definitely used in `ArticleList` to either show the placeholder articles or the actual articles once loaded. A lot of this stuff has already been refactored since this issue was raised I believe.

**Comment by nathggns** [comment]
Sure, but that's just coming from the provider… `ArticleList` still has an unused `isLoading` prop? 

`articlesLoading` is passed by `ArticleList` into each article to show/hide the placeholder. 

Other than removing the unused prop, is there anything else to do here?

**Comment by nathggns** [comment]
Yup, so just an used prop to remove. I'll do that now.
